name: "actions-markdoc"
description: "A simple workflow to run `markdoc` on given file(s)."
author: "OXY2DEV"

branding:
  icon: align-center
  color: gray-dark

inputs:
  config:
    description: "Help file genration configuration"
    required: false
    default: '{ "doc/help.txt": [ "README.md" ] }'
  help_dirs:
    description: "Directories where help files should be generated"
    required: false
    default: '[ "doc" ]'

runs:
  using: "docker"
  image: "Dockerfile"

  args:
    - ${{ inputs.config }}
