name: markdoc
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  doc:
    runs-on: ubuntu-latest
    name: "To vimdoc"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.heade_ref }}
      - uses: OXY2DEV/actions-markdoc@main
        with:
          config: '{ "doc/markdoc.txt": [ "mREADME.md", "README.md" ] }'
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "doc: Generated help files"
          branch: ${{ github.head_ref }}
