name: markdoc
on: [ push ]

permissions:
  contents: write

jobs:
  doc:
    runs-on: ubuntu-latest
    name: "To vimdoc"
    steps:
      - uses: actions/checkout@v2
      - uses: OXY2DEV/markdoc@main
        with:
          config: '{ "doc/markdoc.txt": [ "mREADME.md", "README.md" ] }'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "doc: Generated help files"
          branch: ${{ github.head_ref }}
