name: Release Please

on:
  push:
    branches:
      - main

permissions:
  content: write
  pull-requests: write

jobs:
  release-please:
    - uses: googleapis/release-please-action@v4
      with:
        token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
        release-type: simple
